FROM alpine:3.14

# Update and upgrade packages, install python3
RUN apk update && apk upgrade && apk add --no-cache python3

# Set the working directory
WORKDIR /app
COPY ./listener.py /app/main.py

# Expose port for communication
EXPOSE 8080

# Set the default command
CMD ["python3", "-u", "./main.py"]