server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sandbox
    username: sandbox
    password: sandbox
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      database: 0
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: spring-consumer
      auto-offset-reset: latest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.value.default.type: java.util.HashMap
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  application:
    name: backend

minio:
  endpoint: http://localhost:9000
  accessKey: sandbox
  secretKey: sandbox123
  bucket: sandbox-outputs